
package com.tasly.yzpt.service.wms.sendcannel;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WmsRkxtd", targetNamespace = "http://wservice.rkxtd/", wsdlLocation = "http://10.9.7.31:7001/WmsRkxtd.asmx?wsdl")
public class WmsRkxtd
    extends Service
{

    private final static URL WMSRKXTD_WSDL_LOCATION;
    private final static WebServiceException WMSRKXTD_EXCEPTION;
    private final static QName WMSRKXTD_QNAME = new QName("http://wservice.rkxtd/", "WmsRkxtd");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.9.7.31:7001/WmsRkxtd.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WMSRKXTD_WSDL_LOCATION = url;
        WMSRKXTD_EXCEPTION = e;
    }

    public WmsRkxtd() {
        super(__getWsdlLocation(), WMSRKXTD_QNAME);
    }

    public WmsRkxtd(WebServiceFeature... features) {
        super(__getWsdlLocation(), WMSRKXTD_QNAME, features);
    }

    public WmsRkxtd(URL wsdlLocation) {
        super(wsdlLocation, WMSRKXTD_QNAME);
    }

    public WmsRkxtd(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WMSRKXTD_QNAME, features);
    }

    public WmsRkxtd(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WmsRkxtd(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WmsRkxtdSoap
     */
    @WebEndpoint(name = "WmsRkxtdSoap")
    public WmsRkxtdSoap getWmsRkxtdSoap() {
        return super.getPort(new QName("http://wservice.rkxtd/", "WmsRkxtdSoap"), WmsRkxtdSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WmsRkxtdSoap
     */
    @WebEndpoint(name = "WmsRkxtdSoap")
    public WmsRkxtdSoap getWmsRkxtdSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://wservice.rkxtd/", "WmsRkxtdSoap"), WmsRkxtdSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns WmsRkxtdSoap
     */
    @WebEndpoint(name = "WmsRkxtdSoap12")
    public WmsRkxtdSoap getWmsRkxtdSoap12() {
        return super.getPort(new QName("http://wservice.rkxtd/", "WmsRkxtdSoap12"), WmsRkxtdSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WmsRkxtdSoap
     */
    @WebEndpoint(name = "WmsRkxtdSoap12")
    public WmsRkxtdSoap getWmsRkxtdSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://wservice.rkxtd/", "WmsRkxtdSoap12"), WmsRkxtdSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WMSRKXTD_EXCEPTION!= null) {
            throw WMSRKXTD_EXCEPTION;
        }
        return WMSRKXTD_WSDL_LOCATION;
    }

}
