
package com.tasly.yzpt.service.wms.sendcannel;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WmsRkxtdSoap", targetNamespace = "http://wservice.rkxtd/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WmsRkxtdSoap {


    /**
     * WMS销售退回单下传方法（ERP>LMIS)
     * 
     * @param iREQUEST
     */
    @WebMethod(operationName = "ReceiveRkxtd", action = "http://wservice.rkxtd/ReceiveRkxtd")
    @Oneway
    @RequestWrapper(localName = "ReceiveRkxtd", targetNamespace = "http://wservice.rkxtd/", className = "com.tasly.yzpt.service.wms.sendcannel.ReceiveRkxtd")
    public void receiveRkxtd(
        @WebParam(name = "I_REQUEST", targetNamespace = "http://wservice.rkxtd/")
        INFDATA iREQUEST);

}
