package com.tasly.yzpt.repository.message.entity;

public class OidHanghao {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oid_hanghao.oid
     *
     * @mbg.generated Tue Oct 30 19:04:56 CST 2018
     */
    private String oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oid_hanghao.tid
     *
     * @mbg.generated Tue Oct 30 19:04:56 CST 2018
     */
    private String tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column oid_hanghao.hanghao
     *
     * @mbg.generated Tue Oct 30 19:04:56 CST 2018
     */
    private String hanghao;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oid_hanghao.oid
     *
     * @return the value of oid_hanghao.oid
     *
     * @mbg.generated Tue Oct 30 19:04:56 CST 2018
     */
    public String getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oid_hanghao.oid
     *
     * @param oid the value for oid_hanghao.oid
     *
     * @mbg.generated Tue Oct 30 19:04:56 CST 2018
     */
    public void setOid(String oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oid_hanghao.tid
     *
     * @return the value of oid_hanghao.tid
     *
     * @mbg.generated Tue Oct 30 19:04:56 CST 2018
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oid_hanghao.tid
     *
     * @param tid the value for oid_hanghao.tid
     *
     * @mbg.generated Tue Oct 30 19:04:56 CST 2018
     */
    public void setTid(String tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column oid_hanghao.hanghao
     *
     * @return the value of oid_hanghao.hanghao
     *
     * @mbg.generated Tue Oct 30 19:04:56 CST 2018
     */
    public String getHanghao() {
        return hanghao;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column oid_hanghao.hanghao
     *
     * @param hanghao the value for oid_hanghao.hanghao
     *
     * @mbg.generated Tue Oct 30 19:04:56 CST 2018
     */
    public void setHanghao(String hanghao) {
        this.hanghao = hanghao;
    }
}