package com.tasly.yzpt.repository.message.entity;

public class TidWid {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tid_wid.wid
     *
     * @mbg.generated Fri Oct 26 10:47:11 CST 2018
     */
    private Integer wid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tid_wid.tid
     *
     * @mbg.generated Fri Oct 26 10:47:11 CST 2018
     */
    private String tid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tid_wid.wid
     *
     * @return the value of tid_wid.wid
     *
     * @mbg.generated Fri Oct 26 10:47:11 CST 2018
     */
    public Integer getWid() {
        return wid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tid_wid.wid
     *
     * @param wid the value for tid_wid.wid
     *
     * @mbg.generated Fri Oct 26 10:47:11 CST 2018
     */
    public void setWid(Integer wid) {
        this.wid = wid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tid_wid.tid
     *
     * @return the value of tid_wid.tid
     *
     * @mbg.generated Fri Oct 26 10:47:11 CST 2018
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tid_wid.tid
     *
     * @param tid the value for tid_wid.tid
     *
     * @mbg.generated Fri Oct 26 10:47:11 CST 2018
     */
    public void setTid(String tid) {
        this.tid = tid;
    }
}