package com.tasly.yzpt.repository.message.entity;

import java.math.BigDecimal;

public class TradePay {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_pay.tid
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    private String tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_pay.total_fee
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    private BigDecimal totalFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_pay.post_fee
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    private BigDecimal postFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_pay.payment
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    private BigDecimal payment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_pay.transaction
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    private String transaction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_pay.outer_transactions
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    private String outerTransactions;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_pay.tid
     *
     * @return the value of trade_pay.tid
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_pay.tid
     *
     * @param tid the value for trade_pay.tid
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public void setTid(String tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_pay.total_fee
     *
     * @return the value of trade_pay.total_fee
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public BigDecimal getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_pay.total_fee
     *
     * @param totalFee the value for trade_pay.total_fee
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public void setTotalFee(BigDecimal totalFee) {
        this.totalFee = totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_pay.post_fee
     *
     * @return the value of trade_pay.post_fee
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public BigDecimal getPostFee() {
        return postFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_pay.post_fee
     *
     * @param postFee the value for trade_pay.post_fee
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public void setPostFee(BigDecimal postFee) {
        this.postFee = postFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_pay.payment
     *
     * @return the value of trade_pay.payment
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public BigDecimal getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_pay.payment
     *
     * @param payment the value for trade_pay.payment
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public void setPayment(BigDecimal payment) {
        this.payment = payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_pay.transaction
     *
     * @return the value of trade_pay.transaction
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public String getTransaction() {
        return transaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_pay.transaction
     *
     * @param transaction the value for trade_pay.transaction
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public void setTransaction(String transaction) {
        this.transaction = transaction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_pay.outer_transactions
     *
     * @return the value of trade_pay.outer_transactions
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public String getOuterTransactions() {
        return outerTransactions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_pay.outer_transactions
     *
     * @param outerTransactions the value for trade_pay.outer_transactions
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public void setOuterTransactions(String outerTransactions) {
        this.outerTransactions = outerTransactions;
    }
}