package com.tasly.yzpt.repository.message.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class TradeItemExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_item
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_item
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table trade_item
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_item
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public TradeItemExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_item
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_item
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_item
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_item
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_item
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_item
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_item
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_item
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_item
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table trade_item
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trade_item
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOidIsNull() {
            addCriterion("oid is null");
            return (Criteria) this;
        }

        public Criteria andOidIsNotNull() {
            addCriterion("oid is not null");
            return (Criteria) this;
        }

        public Criteria andOidEqualTo(String value) {
            addCriterion("oid =", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidNotEqualTo(String value) {
            addCriterion("oid <>", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidGreaterThan(String value) {
            addCriterion("oid >", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidGreaterThanOrEqualTo(String value) {
            addCriterion("oid >=", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidLessThan(String value) {
            addCriterion("oid <", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidLessThanOrEqualTo(String value) {
            addCriterion("oid <=", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidLike(String value) {
            addCriterion("oid like", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidNotLike(String value) {
            addCriterion("oid not like", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidIn(List<String> values) {
            addCriterion("oid in", values, "oid");
            return (Criteria) this;
        }

        public Criteria andOidNotIn(List<String> values) {
            addCriterion("oid not in", values, "oid");
            return (Criteria) this;
        }

        public Criteria andOidBetween(String value1, String value2) {
            addCriterion("oid between", value1, value2, "oid");
            return (Criteria) this;
        }

        public Criteria andOidNotBetween(String value1, String value2) {
            addCriterion("oid not between", value1, value2, "oid");
            return (Criteria) this;
        }

        public Criteria andTidIsNull() {
            addCriterion("tid is null");
            return (Criteria) this;
        }

        public Criteria andTidIsNotNull() {
            addCriterion("tid is not null");
            return (Criteria) this;
        }

        public Criteria andTidEqualTo(String value) {
            addCriterion("tid =", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidNotEqualTo(String value) {
            addCriterion("tid <>", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidGreaterThan(String value) {
            addCriterion("tid >", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidGreaterThanOrEqualTo(String value) {
            addCriterion("tid >=", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidLessThan(String value) {
            addCriterion("tid <", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidLessThanOrEqualTo(String value) {
            addCriterion("tid <=", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidLike(String value) {
            addCriterion("tid like", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidNotLike(String value) {
            addCriterion("tid not like", value, "tid");
            return (Criteria) this;
        }

        public Criteria andTidIn(List<String> values) {
            addCriterion("tid in", values, "tid");
            return (Criteria) this;
        }

        public Criteria andTidNotIn(List<String> values) {
            addCriterion("tid not in", values, "tid");
            return (Criteria) this;
        }

        public Criteria andTidBetween(String value1, String value2) {
            addCriterion("tid between", value1, value2, "tid");
            return (Criteria) this;
        }

        public Criteria andTidNotBetween(String value1, String value2) {
            addCriterion("tid not between", value1, value2, "tid");
            return (Criteria) this;
        }

        public Criteria andItemTypeIsNull() {
            addCriterion("item_type is null");
            return (Criteria) this;
        }

        public Criteria andItemTypeIsNotNull() {
            addCriterion("item_type is not null");
            return (Criteria) this;
        }

        public Criteria andItemTypeEqualTo(Integer value) {
            addCriterion("item_type =", value, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeNotEqualTo(Integer value) {
            addCriterion("item_type <>", value, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeGreaterThan(Integer value) {
            addCriterion("item_type >", value, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("item_type >=", value, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeLessThan(Integer value) {
            addCriterion("item_type <", value, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeLessThanOrEqualTo(Integer value) {
            addCriterion("item_type <=", value, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeIn(List<Integer> values) {
            addCriterion("item_type in", values, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeNotIn(List<Integer> values) {
            addCriterion("item_type not in", values, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeBetween(Integer value1, Integer value2) {
            addCriterion("item_type between", value1, value2, "itemType");
            return (Criteria) this;
        }

        public Criteria andItemTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("item_type not between", value1, value2, "itemType");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andNumIsNull() {
            addCriterion("num is null");
            return (Criteria) this;
        }

        public Criteria andNumIsNotNull() {
            addCriterion("num is not null");
            return (Criteria) this;
        }

        public Criteria andNumEqualTo(Integer value) {
            addCriterion("num =", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotEqualTo(Integer value) {
            addCriterion("num <>", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThan(Integer value) {
            addCriterion("num >", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("num >=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThan(Integer value) {
            addCriterion("num <", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumLessThanOrEqualTo(Integer value) {
            addCriterion("num <=", value, "num");
            return (Criteria) this;
        }

        public Criteria andNumIn(List<Integer> values) {
            addCriterion("num in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotIn(List<Integer> values) {
            addCriterion("num not in", values, "num");
            return (Criteria) this;
        }

        public Criteria andNumBetween(Integer value1, Integer value2) {
            addCriterion("num between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andNumNotBetween(Integer value1, Integer value2) {
            addCriterion("num not between", value1, value2, "num");
            return (Criteria) this;
        }

        public Criteria andOuterSkuIdIsNull() {
            addCriterion("outer_sku_id is null");
            return (Criteria) this;
        }

        public Criteria andOuterSkuIdIsNotNull() {
            addCriterion("outer_sku_id is not null");
            return (Criteria) this;
        }

        public Criteria andOuterSkuIdEqualTo(String value) {
            addCriterion("outer_sku_id =", value, "outerSkuId");
            return (Criteria) this;
        }

        public Criteria andOuterSkuIdNotEqualTo(String value) {
            addCriterion("outer_sku_id <>", value, "outerSkuId");
            return (Criteria) this;
        }

        public Criteria andOuterSkuIdGreaterThan(String value) {
            addCriterion("outer_sku_id >", value, "outerSkuId");
            return (Criteria) this;
        }

        public Criteria andOuterSkuIdGreaterThanOrEqualTo(String value) {
            addCriterion("outer_sku_id >=", value, "outerSkuId");
            return (Criteria) this;
        }

        public Criteria andOuterSkuIdLessThan(String value) {
            addCriterion("outer_sku_id <", value, "outerSkuId");
            return (Criteria) this;
        }

        public Criteria andOuterSkuIdLessThanOrEqualTo(String value) {
            addCriterion("outer_sku_id <=", value, "outerSkuId");
            return (Criteria) this;
        }

        public Criteria andOuterSkuIdLike(String value) {
            addCriterion("outer_sku_id like", value, "outerSkuId");
            return (Criteria) this;
        }

        public Criteria andOuterSkuIdNotLike(String value) {
            addCriterion("outer_sku_id not like", value, "outerSkuId");
            return (Criteria) this;
        }

        public Criteria andOuterSkuIdIn(List<String> values) {
            addCriterion("outer_sku_id in", values, "outerSkuId");
            return (Criteria) this;
        }

        public Criteria andOuterSkuIdNotIn(List<String> values) {
            addCriterion("outer_sku_id not in", values, "outerSkuId");
            return (Criteria) this;
        }

        public Criteria andOuterSkuIdBetween(String value1, String value2) {
            addCriterion("outer_sku_id between", value1, value2, "outerSkuId");
            return (Criteria) this;
        }

        public Criteria andOuterSkuIdNotBetween(String value1, String value2) {
            addCriterion("outer_sku_id not between", value1, value2, "outerSkuId");
            return (Criteria) this;
        }

        public Criteria andBuyerMessagesIsNull() {
            addCriterion("buyer_messages is null");
            return (Criteria) this;
        }

        public Criteria andBuyerMessagesIsNotNull() {
            addCriterion("buyer_messages is not null");
            return (Criteria) this;
        }

        public Criteria andBuyerMessagesEqualTo(String value) {
            addCriterion("buyer_messages =", value, "buyerMessages");
            return (Criteria) this;
        }

        public Criteria andBuyerMessagesNotEqualTo(String value) {
            addCriterion("buyer_messages <>", value, "buyerMessages");
            return (Criteria) this;
        }

        public Criteria andBuyerMessagesGreaterThan(String value) {
            addCriterion("buyer_messages >", value, "buyerMessages");
            return (Criteria) this;
        }

        public Criteria andBuyerMessagesGreaterThanOrEqualTo(String value) {
            addCriterion("buyer_messages >=", value, "buyerMessages");
            return (Criteria) this;
        }

        public Criteria andBuyerMessagesLessThan(String value) {
            addCriterion("buyer_messages <", value, "buyerMessages");
            return (Criteria) this;
        }

        public Criteria andBuyerMessagesLessThanOrEqualTo(String value) {
            addCriterion("buyer_messages <=", value, "buyerMessages");
            return (Criteria) this;
        }

        public Criteria andBuyerMessagesLike(String value) {
            addCriterion("buyer_messages like", value, "buyerMessages");
            return (Criteria) this;
        }

        public Criteria andBuyerMessagesNotLike(String value) {
            addCriterion("buyer_messages not like", value, "buyerMessages");
            return (Criteria) this;
        }

        public Criteria andBuyerMessagesIn(List<String> values) {
            addCriterion("buyer_messages in", values, "buyerMessages");
            return (Criteria) this;
        }

        public Criteria andBuyerMessagesNotIn(List<String> values) {
            addCriterion("buyer_messages not in", values, "buyerMessages");
            return (Criteria) this;
        }

        public Criteria andBuyerMessagesBetween(String value1, String value2) {
            addCriterion("buyer_messages between", value1, value2, "buyerMessages");
            return (Criteria) this;
        }

        public Criteria andBuyerMessagesNotBetween(String value1, String value2) {
            addCriterion("buyer_messages not between", value1, value2, "buyerMessages");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("price is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("price is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(BigDecimal value) {
            addCriterion("price =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(BigDecimal value) {
            addCriterion("price <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(BigDecimal value) {
            addCriterion("price >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("price >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(BigDecimal value) {
            addCriterion("price <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("price <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<BigDecimal> values) {
            addCriterion("price in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<BigDecimal> values) {
            addCriterion("price not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("price not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andTotalFeeIsNull() {
            addCriterion("total_fee is null");
            return (Criteria) this;
        }

        public Criteria andTotalFeeIsNotNull() {
            addCriterion("total_fee is not null");
            return (Criteria) this;
        }

        public Criteria andTotalFeeEqualTo(BigDecimal value) {
            addCriterion("total_fee =", value, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeNotEqualTo(BigDecimal value) {
            addCriterion("total_fee <>", value, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeGreaterThan(BigDecimal value) {
            addCriterion("total_fee >", value, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("total_fee >=", value, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeLessThan(BigDecimal value) {
            addCriterion("total_fee <", value, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeLessThanOrEqualTo(BigDecimal value) {
            addCriterion("total_fee <=", value, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeIn(List<BigDecimal> values) {
            addCriterion("total_fee in", values, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeNotIn(List<BigDecimal> values) {
            addCriterion("total_fee not in", values, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_fee between", value1, value2, "totalFee");
            return (Criteria) this;
        }

        public Criteria andTotalFeeNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("total_fee not between", value1, value2, "totalFee");
            return (Criteria) this;
        }

        public Criteria andPaymentIsNull() {
            addCriterion("payment is null");
            return (Criteria) this;
        }

        public Criteria andPaymentIsNotNull() {
            addCriterion("payment is not null");
            return (Criteria) this;
        }

        public Criteria andPaymentEqualTo(Long value) {
            addCriterion("payment =", value, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentNotEqualTo(Long value) {
            addCriterion("payment <>", value, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentGreaterThan(Long value) {
            addCriterion("payment >", value, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentGreaterThanOrEqualTo(Long value) {
            addCriterion("payment >=", value, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentLessThan(Long value) {
            addCriterion("payment <", value, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentLessThanOrEqualTo(Long value) {
            addCriterion("payment <=", value, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentIn(List<Long> values) {
            addCriterion("payment in", values, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentNotIn(List<Long> values) {
            addCriterion("payment not in", values, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentBetween(Long value1, Long value2) {
            addCriterion("payment between", value1, value2, "payment");
            return (Criteria) this;
        }

        public Criteria andPaymentNotBetween(Long value1, Long value2) {
            addCriterion("payment not between", value1, value2, "payment");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNull() {
            addCriterion("item_id is null");
            return (Criteria) this;
        }

        public Criteria andItemIdIsNotNull() {
            addCriterion("item_id is not null");
            return (Criteria) this;
        }

        public Criteria andItemIdEqualTo(Integer value) {
            addCriterion("item_id =", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotEqualTo(Integer value) {
            addCriterion("item_id <>", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThan(Integer value) {
            addCriterion("item_id >", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("item_id >=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThan(Integer value) {
            addCriterion("item_id <", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdLessThanOrEqualTo(Integer value) {
            addCriterion("item_id <=", value, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdIn(List<Integer> values) {
            addCriterion("item_id in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotIn(List<Integer> values) {
            addCriterion("item_id not in", values, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdBetween(Integer value1, Integer value2) {
            addCriterion("item_id between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andItemIdNotBetween(Integer value1, Integer value2) {
            addCriterion("item_id not between", value1, value2, "itemId");
            return (Criteria) this;
        }

        public Criteria andSkuIdIsNull() {
            addCriterion("sku_id is null");
            return (Criteria) this;
        }

        public Criteria andSkuIdIsNotNull() {
            addCriterion("sku_id is not null");
            return (Criteria) this;
        }

        public Criteria andSkuIdEqualTo(Integer value) {
            addCriterion("sku_id =", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdNotEqualTo(Integer value) {
            addCriterion("sku_id <>", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdGreaterThan(Integer value) {
            addCriterion("sku_id >", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("sku_id >=", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdLessThan(Integer value) {
            addCriterion("sku_id <", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdLessThanOrEqualTo(Integer value) {
            addCriterion("sku_id <=", value, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdIn(List<Integer> values) {
            addCriterion("sku_id in", values, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdNotIn(List<Integer> values) {
            addCriterion("sku_id not in", values, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdBetween(Integer value1, Integer value2) {
            addCriterion("sku_id between", value1, value2, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuIdNotBetween(Integer value1, Integer value2) {
            addCriterion("sku_id not between", value1, value2, "skuId");
            return (Criteria) this;
        }

        public Criteria andSkuPropertiesNameIsNull() {
            addCriterion("sku_properties_name is null");
            return (Criteria) this;
        }

        public Criteria andSkuPropertiesNameIsNotNull() {
            addCriterion("sku_properties_name is not null");
            return (Criteria) this;
        }

        public Criteria andSkuPropertiesNameEqualTo(String value) {
            addCriterion("sku_properties_name =", value, "skuPropertiesName");
            return (Criteria) this;
        }

        public Criteria andSkuPropertiesNameNotEqualTo(String value) {
            addCriterion("sku_properties_name <>", value, "skuPropertiesName");
            return (Criteria) this;
        }

        public Criteria andSkuPropertiesNameGreaterThan(String value) {
            addCriterion("sku_properties_name >", value, "skuPropertiesName");
            return (Criteria) this;
        }

        public Criteria andSkuPropertiesNameGreaterThanOrEqualTo(String value) {
            addCriterion("sku_properties_name >=", value, "skuPropertiesName");
            return (Criteria) this;
        }

        public Criteria andSkuPropertiesNameLessThan(String value) {
            addCriterion("sku_properties_name <", value, "skuPropertiesName");
            return (Criteria) this;
        }

        public Criteria andSkuPropertiesNameLessThanOrEqualTo(String value) {
            addCriterion("sku_properties_name <=", value, "skuPropertiesName");
            return (Criteria) this;
        }

        public Criteria andSkuPropertiesNameLike(String value) {
            addCriterion("sku_properties_name like", value, "skuPropertiesName");
            return (Criteria) this;
        }

        public Criteria andSkuPropertiesNameNotLike(String value) {
            addCriterion("sku_properties_name not like", value, "skuPropertiesName");
            return (Criteria) this;
        }

        public Criteria andSkuPropertiesNameIn(List<String> values) {
            addCriterion("sku_properties_name in", values, "skuPropertiesName");
            return (Criteria) this;
        }

        public Criteria andSkuPropertiesNameNotIn(List<String> values) {
            addCriterion("sku_properties_name not in", values, "skuPropertiesName");
            return (Criteria) this;
        }

        public Criteria andSkuPropertiesNameBetween(String value1, String value2) {
            addCriterion("sku_properties_name between", value1, value2, "skuPropertiesName");
            return (Criteria) this;
        }

        public Criteria andSkuPropertiesNameNotBetween(String value1, String value2) {
            addCriterion("sku_properties_name not between", value1, value2, "skuPropertiesName");
            return (Criteria) this;
        }

        public Criteria andOuterItemIdIsNull() {
            addCriterion("outer_item_id is null");
            return (Criteria) this;
        }

        public Criteria andOuterItemIdIsNotNull() {
            addCriterion("outer_item_id is not null");
            return (Criteria) this;
        }

        public Criteria andOuterItemIdEqualTo(String value) {
            addCriterion("outer_item_id =", value, "outerItemId");
            return (Criteria) this;
        }

        public Criteria andOuterItemIdNotEqualTo(String value) {
            addCriterion("outer_item_id <>", value, "outerItemId");
            return (Criteria) this;
        }

        public Criteria andOuterItemIdGreaterThan(String value) {
            addCriterion("outer_item_id >", value, "outerItemId");
            return (Criteria) this;
        }

        public Criteria andOuterItemIdGreaterThanOrEqualTo(String value) {
            addCriterion("outer_item_id >=", value, "outerItemId");
            return (Criteria) this;
        }

        public Criteria andOuterItemIdLessThan(String value) {
            addCriterion("outer_item_id <", value, "outerItemId");
            return (Criteria) this;
        }

        public Criteria andOuterItemIdLessThanOrEqualTo(String value) {
            addCriterion("outer_item_id <=", value, "outerItemId");
            return (Criteria) this;
        }

        public Criteria andOuterItemIdLike(String value) {
            addCriterion("outer_item_id like", value, "outerItemId");
            return (Criteria) this;
        }

        public Criteria andOuterItemIdNotLike(String value) {
            addCriterion("outer_item_id not like", value, "outerItemId");
            return (Criteria) this;
        }

        public Criteria andOuterItemIdIn(List<String> values) {
            addCriterion("outer_item_id in", values, "outerItemId");
            return (Criteria) this;
        }

        public Criteria andOuterItemIdNotIn(List<String> values) {
            addCriterion("outer_item_id not in", values, "outerItemId");
            return (Criteria) this;
        }

        public Criteria andOuterItemIdBetween(String value1, String value2) {
            addCriterion("outer_item_id between", value1, value2, "outerItemId");
            return (Criteria) this;
        }

        public Criteria andOuterItemIdNotBetween(String value1, String value2) {
            addCriterion("outer_item_id not between", value1, value2, "outerItemId");
            return (Criteria) this;
        }

        public Criteria andPointsPriceIsNull() {
            addCriterion("points_price is null");
            return (Criteria) this;
        }

        public Criteria andPointsPriceIsNotNull() {
            addCriterion("points_price is not null");
            return (Criteria) this;
        }

        public Criteria andPointsPriceEqualTo(String value) {
            addCriterion("points_price =", value, "pointsPrice");
            return (Criteria) this;
        }

        public Criteria andPointsPriceNotEqualTo(String value) {
            addCriterion("points_price <>", value, "pointsPrice");
            return (Criteria) this;
        }

        public Criteria andPointsPriceGreaterThan(String value) {
            addCriterion("points_price >", value, "pointsPrice");
            return (Criteria) this;
        }

        public Criteria andPointsPriceGreaterThanOrEqualTo(String value) {
            addCriterion("points_price >=", value, "pointsPrice");
            return (Criteria) this;
        }

        public Criteria andPointsPriceLessThan(String value) {
            addCriterion("points_price <", value, "pointsPrice");
            return (Criteria) this;
        }

        public Criteria andPointsPriceLessThanOrEqualTo(String value) {
            addCriterion("points_price <=", value, "pointsPrice");
            return (Criteria) this;
        }

        public Criteria andPointsPriceLike(String value) {
            addCriterion("points_price like", value, "pointsPrice");
            return (Criteria) this;
        }

        public Criteria andPointsPriceNotLike(String value) {
            addCriterion("points_price not like", value, "pointsPrice");
            return (Criteria) this;
        }

        public Criteria andPointsPriceIn(List<String> values) {
            addCriterion("points_price in", values, "pointsPrice");
            return (Criteria) this;
        }

        public Criteria andPointsPriceNotIn(List<String> values) {
            addCriterion("points_price not in", values, "pointsPrice");
            return (Criteria) this;
        }

        public Criteria andPointsPriceBetween(String value1, String value2) {
            addCriterion("points_price between", value1, value2, "pointsPrice");
            return (Criteria) this;
        }

        public Criteria andPointsPriceNotBetween(String value1, String value2) {
            addCriterion("points_price not between", value1, value2, "pointsPrice");
            return (Criteria) this;
        }

        public Criteria andPicPathIsNull() {
            addCriterion("pic_path is null");
            return (Criteria) this;
        }

        public Criteria andPicPathIsNotNull() {
            addCriterion("pic_path is not null");
            return (Criteria) this;
        }

        public Criteria andPicPathEqualTo(String value) {
            addCriterion("pic_path =", value, "picPath");
            return (Criteria) this;
        }

        public Criteria andPicPathNotEqualTo(String value) {
            addCriterion("pic_path <>", value, "picPath");
            return (Criteria) this;
        }

        public Criteria andPicPathGreaterThan(String value) {
            addCriterion("pic_path >", value, "picPath");
            return (Criteria) this;
        }

        public Criteria andPicPathGreaterThanOrEqualTo(String value) {
            addCriterion("pic_path >=", value, "picPath");
            return (Criteria) this;
        }

        public Criteria andPicPathLessThan(String value) {
            addCriterion("pic_path <", value, "picPath");
            return (Criteria) this;
        }

        public Criteria andPicPathLessThanOrEqualTo(String value) {
            addCriterion("pic_path <=", value, "picPath");
            return (Criteria) this;
        }

        public Criteria andPicPathLike(String value) {
            addCriterion("pic_path like", value, "picPath");
            return (Criteria) this;
        }

        public Criteria andPicPathNotLike(String value) {
            addCriterion("pic_path not like", value, "picPath");
            return (Criteria) this;
        }

        public Criteria andPicPathIn(List<String> values) {
            addCriterion("pic_path in", values, "picPath");
            return (Criteria) this;
        }

        public Criteria andPicPathNotIn(List<String> values) {
            addCriterion("pic_path not in", values, "picPath");
            return (Criteria) this;
        }

        public Criteria andPicPathBetween(String value1, String value2) {
            addCriterion("pic_path between", value1, value2, "picPath");
            return (Criteria) this;
        }

        public Criteria andPicPathNotBetween(String value1, String value2) {
            addCriterion("pic_path not between", value1, value2, "picPath");
            return (Criteria) this;
        }

        public Criteria andGoodsUrlIsNull() {
            addCriterion("goods_url is null");
            return (Criteria) this;
        }

        public Criteria andGoodsUrlIsNotNull() {
            addCriterion("goods_url is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsUrlEqualTo(String value) {
            addCriterion("goods_url =", value, "goodsUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsUrlNotEqualTo(String value) {
            addCriterion("goods_url <>", value, "goodsUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsUrlGreaterThan(String value) {
            addCriterion("goods_url >", value, "goodsUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsUrlGreaterThanOrEqualTo(String value) {
            addCriterion("goods_url >=", value, "goodsUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsUrlLessThan(String value) {
            addCriterion("goods_url <", value, "goodsUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsUrlLessThanOrEqualTo(String value) {
            addCriterion("goods_url <=", value, "goodsUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsUrlLike(String value) {
            addCriterion("goods_url like", value, "goodsUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsUrlNotLike(String value) {
            addCriterion("goods_url not like", value, "goodsUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsUrlIn(List<String> values) {
            addCriterion("goods_url in", values, "goodsUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsUrlNotIn(List<String> values) {
            addCriterion("goods_url not in", values, "goodsUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsUrlBetween(String value1, String value2) {
            addCriterion("goods_url between", value1, value2, "goodsUrl");
            return (Criteria) this;
        }

        public Criteria andGoodsUrlNotBetween(String value1, String value2) {
            addCriterion("goods_url not between", value1, value2, "goodsUrl");
            return (Criteria) this;
        }

        public Criteria andAliasIsNull() {
            addCriterion("alias is null");
            return (Criteria) this;
        }

        public Criteria andAliasIsNotNull() {
            addCriterion("alias is not null");
            return (Criteria) this;
        }

        public Criteria andAliasEqualTo(String value) {
            addCriterion("alias =", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasNotEqualTo(String value) {
            addCriterion("alias <>", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasGreaterThan(String value) {
            addCriterion("alias >", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasGreaterThanOrEqualTo(String value) {
            addCriterion("alias >=", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasLessThan(String value) {
            addCriterion("alias <", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasLessThanOrEqualTo(String value) {
            addCriterion("alias <=", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasLike(String value) {
            addCriterion("alias like", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasNotLike(String value) {
            addCriterion("alias not like", value, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasIn(List<String> values) {
            addCriterion("alias in", values, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasNotIn(List<String> values) {
            addCriterion("alias not in", values, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasBetween(String value1, String value2) {
            addCriterion("alias between", value1, value2, "alias");
            return (Criteria) this;
        }

        public Criteria andAliasNotBetween(String value1, String value2) {
            addCriterion("alias not between", value1, value2, "alias");
            return (Criteria) this;
        }

        public Criteria andIsPresentIsNull() {
            addCriterion("is_present is null");
            return (Criteria) this;
        }

        public Criteria andIsPresentIsNotNull() {
            addCriterion("is_present is not null");
            return (Criteria) this;
        }

        public Criteria andIsPresentEqualTo(Boolean value) {
            addCriterion("is_present =", value, "isPresent");
            return (Criteria) this;
        }

        public Criteria andIsPresentNotEqualTo(Boolean value) {
            addCriterion("is_present <>", value, "isPresent");
            return (Criteria) this;
        }

        public Criteria andIsPresentGreaterThan(Boolean value) {
            addCriterion("is_present >", value, "isPresent");
            return (Criteria) this;
        }

        public Criteria andIsPresentGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_present >=", value, "isPresent");
            return (Criteria) this;
        }

        public Criteria andIsPresentLessThan(Boolean value) {
            addCriterion("is_present <", value, "isPresent");
            return (Criteria) this;
        }

        public Criteria andIsPresentLessThanOrEqualTo(Boolean value) {
            addCriterion("is_present <=", value, "isPresent");
            return (Criteria) this;
        }

        public Criteria andIsPresentIn(List<Boolean> values) {
            addCriterion("is_present in", values, "isPresent");
            return (Criteria) this;
        }

        public Criteria andIsPresentNotIn(List<Boolean> values) {
            addCriterion("is_present not in", values, "isPresent");
            return (Criteria) this;
        }

        public Criteria andIsPresentBetween(Boolean value1, Boolean value2) {
            addCriterion("is_present between", value1, value2, "isPresent");
            return (Criteria) this;
        }

        public Criteria andIsPresentNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_present not between", value1, value2, "isPresent");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceIsNull() {
            addCriterion("discount_price is null");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceIsNotNull() {
            addCriterion("discount_price is not null");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceEqualTo(BigDecimal value) {
            addCriterion("discount_price =", value, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceNotEqualTo(BigDecimal value) {
            addCriterion("discount_price <>", value, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceGreaterThan(BigDecimal value) {
            addCriterion("discount_price >", value, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("discount_price >=", value, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceLessThan(BigDecimal value) {
            addCriterion("discount_price <", value, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("discount_price <=", value, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceIn(List<BigDecimal> values) {
            addCriterion("discount_price in", values, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceNotIn(List<BigDecimal> values) {
            addCriterion("discount_price not in", values, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("discount_price between", value1, value2, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andDiscountPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("discount_price not between", value1, value2, "discountPrice");
            return (Criteria) this;
        }

        public Criteria andSkuUniqueCodeIsNull() {
            addCriterion("sku_unique_code is null");
            return (Criteria) this;
        }

        public Criteria andSkuUniqueCodeIsNotNull() {
            addCriterion("sku_unique_code is not null");
            return (Criteria) this;
        }

        public Criteria andSkuUniqueCodeEqualTo(String value) {
            addCriterion("sku_unique_code =", value, "skuUniqueCode");
            return (Criteria) this;
        }

        public Criteria andSkuUniqueCodeNotEqualTo(String value) {
            addCriterion("sku_unique_code <>", value, "skuUniqueCode");
            return (Criteria) this;
        }

        public Criteria andSkuUniqueCodeGreaterThan(String value) {
            addCriterion("sku_unique_code >", value, "skuUniqueCode");
            return (Criteria) this;
        }

        public Criteria andSkuUniqueCodeGreaterThanOrEqualTo(String value) {
            addCriterion("sku_unique_code >=", value, "skuUniqueCode");
            return (Criteria) this;
        }

        public Criteria andSkuUniqueCodeLessThan(String value) {
            addCriterion("sku_unique_code <", value, "skuUniqueCode");
            return (Criteria) this;
        }

        public Criteria andSkuUniqueCodeLessThanOrEqualTo(String value) {
            addCriterion("sku_unique_code <=", value, "skuUniqueCode");
            return (Criteria) this;
        }

        public Criteria andSkuUniqueCodeLike(String value) {
            addCriterion("sku_unique_code like", value, "skuUniqueCode");
            return (Criteria) this;
        }

        public Criteria andSkuUniqueCodeNotLike(String value) {
            addCriterion("sku_unique_code not like", value, "skuUniqueCode");
            return (Criteria) this;
        }

        public Criteria andSkuUniqueCodeIn(List<String> values) {
            addCriterion("sku_unique_code in", values, "skuUniqueCode");
            return (Criteria) this;
        }

        public Criteria andSkuUniqueCodeNotIn(List<String> values) {
            addCriterion("sku_unique_code not in", values, "skuUniqueCode");
            return (Criteria) this;
        }

        public Criteria andSkuUniqueCodeBetween(String value1, String value2) {
            addCriterion("sku_unique_code between", value1, value2, "skuUniqueCode");
            return (Criteria) this;
        }

        public Criteria andSkuUniqueCodeNotBetween(String value1, String value2) {
            addCriterion("sku_unique_code not between", value1, value2, "skuUniqueCode");
            return (Criteria) this;
        }

        public Criteria andPreSaleTypeIsNull() {
            addCriterion("pre_sale_type is null");
            return (Criteria) this;
        }

        public Criteria andPreSaleTypeIsNotNull() {
            addCriterion("pre_sale_type is not null");
            return (Criteria) this;
        }

        public Criteria andPreSaleTypeEqualTo(String value) {
            addCriterion("pre_sale_type =", value, "preSaleType");
            return (Criteria) this;
        }

        public Criteria andPreSaleTypeNotEqualTo(String value) {
            addCriterion("pre_sale_type <>", value, "preSaleType");
            return (Criteria) this;
        }

        public Criteria andPreSaleTypeGreaterThan(String value) {
            addCriterion("pre_sale_type >", value, "preSaleType");
            return (Criteria) this;
        }

        public Criteria andPreSaleTypeGreaterThanOrEqualTo(String value) {
            addCriterion("pre_sale_type >=", value, "preSaleType");
            return (Criteria) this;
        }

        public Criteria andPreSaleTypeLessThan(String value) {
            addCriterion("pre_sale_type <", value, "preSaleType");
            return (Criteria) this;
        }

        public Criteria andPreSaleTypeLessThanOrEqualTo(String value) {
            addCriterion("pre_sale_type <=", value, "preSaleType");
            return (Criteria) this;
        }

        public Criteria andPreSaleTypeLike(String value) {
            addCriterion("pre_sale_type like", value, "preSaleType");
            return (Criteria) this;
        }

        public Criteria andPreSaleTypeNotLike(String value) {
            addCriterion("pre_sale_type not like", value, "preSaleType");
            return (Criteria) this;
        }

        public Criteria andPreSaleTypeIn(List<String> values) {
            addCriterion("pre_sale_type in", values, "preSaleType");
            return (Criteria) this;
        }

        public Criteria andPreSaleTypeNotIn(List<String> values) {
            addCriterion("pre_sale_type not in", values, "preSaleType");
            return (Criteria) this;
        }

        public Criteria andPreSaleTypeBetween(String value1, String value2) {
            addCriterion("pre_sale_type between", value1, value2, "preSaleType");
            return (Criteria) this;
        }

        public Criteria andPreSaleTypeNotBetween(String value1, String value2) {
            addCriterion("pre_sale_type not between", value1, value2, "preSaleType");
            return (Criteria) this;
        }

        public Criteria andIsPreSaleIsNull() {
            addCriterion("is_pre_sale is null");
            return (Criteria) this;
        }

        public Criteria andIsPreSaleIsNotNull() {
            addCriterion("is_pre_sale is not null");
            return (Criteria) this;
        }

        public Criteria andIsPreSaleEqualTo(String value) {
            addCriterion("is_pre_sale =", value, "isPreSale");
            return (Criteria) this;
        }

        public Criteria andIsPreSaleNotEqualTo(String value) {
            addCriterion("is_pre_sale <>", value, "isPreSale");
            return (Criteria) this;
        }

        public Criteria andIsPreSaleGreaterThan(String value) {
            addCriterion("is_pre_sale >", value, "isPreSale");
            return (Criteria) this;
        }

        public Criteria andIsPreSaleGreaterThanOrEqualTo(String value) {
            addCriterion("is_pre_sale >=", value, "isPreSale");
            return (Criteria) this;
        }

        public Criteria andIsPreSaleLessThan(String value) {
            addCriterion("is_pre_sale <", value, "isPreSale");
            return (Criteria) this;
        }

        public Criteria andIsPreSaleLessThanOrEqualTo(String value) {
            addCriterion("is_pre_sale <=", value, "isPreSale");
            return (Criteria) this;
        }

        public Criteria andIsPreSaleLike(String value) {
            addCriterion("is_pre_sale like", value, "isPreSale");
            return (Criteria) this;
        }

        public Criteria andIsPreSaleNotLike(String value) {
            addCriterion("is_pre_sale not like", value, "isPreSale");
            return (Criteria) this;
        }

        public Criteria andIsPreSaleIn(List<String> values) {
            addCriterion("is_pre_sale in", values, "isPreSale");
            return (Criteria) this;
        }

        public Criteria andIsPreSaleNotIn(List<String> values) {
            addCriterion("is_pre_sale not in", values, "isPreSale");
            return (Criteria) this;
        }

        public Criteria andIsPreSaleBetween(String value1, String value2) {
            addCriterion("is_pre_sale between", value1, value2, "isPreSale");
            return (Criteria) this;
        }

        public Criteria andIsPreSaleNotBetween(String value1, String value2) {
            addCriterion("is_pre_sale not between", value1, value2, "isPreSale");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trade_item
     *
     * @mbg.generated do_not_delete_during_merge Fri Oct 19 09:30:28 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table trade_item
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}