package com.tasly.yzpt.repository.message.entity;

import java.util.Date;

public class TradeInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_info.tid
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private String tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_info.status
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_info.type
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_info.status_str
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private String statusStr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_info.pay_type
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private Integer payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_info.team_type
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private Integer teamType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_info.close_type
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private Integer closeType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_info.express_type
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private Integer expressType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_info.created_time
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private Date createdTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_info.update_time
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_info.expired_time
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private Date expiredTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_info.pay_time
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private Date payTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_info.consign_time
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private Date consignTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_info.confirm_time
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private Date confirmTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_info.refund_state
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private Integer refundState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_info.is_retail_order
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private Boolean isRetailOrder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_info.success_time
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private Date successTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_info.offline_id
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private Integer offlineId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_info.pay_type_str
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private String payTypeStr;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_info.tid
     *
     * @return the value of trade_info.tid
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_info.tid
     *
     * @param tid the value for trade_info.tid
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setTid(String tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_info.status
     *
     * @return the value of trade_info.status
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_info.status
     *
     * @param status the value for trade_info.status
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_info.type
     *
     * @return the value of trade_info.type
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_info.type
     *
     * @param type the value for trade_info.type
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_info.status_str
     *
     * @return the value of trade_info.status_str
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public String getStatusStr() {
        return statusStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_info.status_str
     *
     * @param statusStr the value for trade_info.status_str
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setStatusStr(String statusStr) {
        this.statusStr = statusStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_info.pay_type
     *
     * @return the value of trade_info.pay_type
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_info.pay_type
     *
     * @param payType the value for trade_info.pay_type
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_info.team_type
     *
     * @return the value of trade_info.team_type
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public Integer getTeamType() {
        return teamType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_info.team_type
     *
     * @param teamType the value for trade_info.team_type
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setTeamType(Integer teamType) {
        this.teamType = teamType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_info.close_type
     *
     * @return the value of trade_info.close_type
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public Integer getCloseType() {
        return closeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_info.close_type
     *
     * @param closeType the value for trade_info.close_type
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setCloseType(Integer closeType) {
        this.closeType = closeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_info.express_type
     *
     * @return the value of trade_info.express_type
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public Integer getExpressType() {
        return expressType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_info.express_type
     *
     * @param expressType the value for trade_info.express_type
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setExpressType(Integer expressType) {
        this.expressType = expressType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_info.created_time
     *
     * @return the value of trade_info.created_time
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public Date getCreatedTime() {
        return createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_info.created_time
     *
     * @param createdTime the value for trade_info.created_time
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setCreatedTime(Date createdTime) {
        this.createdTime = createdTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_info.update_time
     *
     * @return the value of trade_info.update_time
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_info.update_time
     *
     * @param updateTime the value for trade_info.update_time
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_info.expired_time
     *
     * @return the value of trade_info.expired_time
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public Date getExpiredTime() {
        return expiredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_info.expired_time
     *
     * @param expiredTime the value for trade_info.expired_time
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setExpiredTime(Date expiredTime) {
        this.expiredTime = expiredTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_info.pay_time
     *
     * @return the value of trade_info.pay_time
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_info.pay_time
     *
     * @param payTime the value for trade_info.pay_time
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_info.consign_time
     *
     * @return the value of trade_info.consign_time
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public Date getConsignTime() {
        return consignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_info.consign_time
     *
     * @param consignTime the value for trade_info.consign_time
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setConsignTime(Date consignTime) {
        this.consignTime = consignTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_info.confirm_time
     *
     * @return the value of trade_info.confirm_time
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public Date getConfirmTime() {
        return confirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_info.confirm_time
     *
     * @param confirmTime the value for trade_info.confirm_time
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setConfirmTime(Date confirmTime) {
        this.confirmTime = confirmTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_info.refund_state
     *
     * @return the value of trade_info.refund_state
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public Integer getRefundState() {
        return refundState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_info.refund_state
     *
     * @param refundState the value for trade_info.refund_state
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setRefundState(Integer refundState) {
        this.refundState = refundState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_info.is_retail_order
     *
     * @return the value of trade_info.is_retail_order
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public Boolean getIsRetailOrder() {
        return isRetailOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_info.is_retail_order
     *
     * @param isRetailOrder the value for trade_info.is_retail_order
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setIsRetailOrder(Boolean isRetailOrder) {
        this.isRetailOrder = isRetailOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_info.success_time
     *
     * @return the value of trade_info.success_time
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public Date getSuccessTime() {
        return successTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_info.success_time
     *
     * @param successTime the value for trade_info.success_time
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setSuccessTime(Date successTime) {
        this.successTime = successTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_info.offline_id
     *
     * @return the value of trade_info.offline_id
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public Integer getOfflineId() {
        return offlineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_info.offline_id
     *
     * @param offlineId the value for trade_info.offline_id
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setOfflineId(Integer offlineId) {
        this.offlineId = offlineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_info.pay_type_str
     *
     * @return the value of trade_info.pay_type_str
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public String getPayTypeStr() {
        return payTypeStr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_info.pay_type_str
     *
     * @param payTypeStr the value for trade_info.pay_type_str
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setPayTypeStr(String payTypeStr) {
        this.payTypeStr = payTypeStr;
    }
}