package com.tasly.yzpt.repository.message.entity;

import java.math.BigDecimal;
import java.util.Date;

public class TradeRefund {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_refund.refund_id
     *
     * @mbg.generated Tue Oct 30 19:06:11 CST 2018
     */
    private String refundId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_refund.tid
     *
     * @mbg.generated Tue Oct 30 19:06:11 CST 2018
     */
    private String tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_refund.oid
     *
     * @mbg.generated Tue Oct 30 19:06:11 CST 2018
     */
    private String oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_refund.refund_type
     *
     * @mbg.generated Tue Oct 30 19:06:11 CST 2018
     */
    private String refundType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_refund.refunded_fee
     *
     * @mbg.generated Tue Oct 30 19:06:11 CST 2018
     */
    private BigDecimal refundedFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_refund.refund_reason
     *
     * @mbg.generated Tue Oct 30 19:06:11 CST 2018
     */
    private String refundReason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_refund.version
     *
     * @mbg.generated Tue Oct 30 19:06:11 CST 2018
     */
    private String version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_refund.update_time
     *
     * @mbg.generated Tue Oct 30 19:06:11 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_refund.refund_id
     *
     * @return the value of trade_refund.refund_id
     *
     * @mbg.generated Tue Oct 30 19:06:11 CST 2018
     */
    public String getRefundId() {
        return refundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_refund.refund_id
     *
     * @param refundId the value for trade_refund.refund_id
     *
     * @mbg.generated Tue Oct 30 19:06:11 CST 2018
     */
    public void setRefundId(String refundId) {
        this.refundId = refundId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_refund.tid
     *
     * @return the value of trade_refund.tid
     *
     * @mbg.generated Tue Oct 30 19:06:11 CST 2018
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_refund.tid
     *
     * @param tid the value for trade_refund.tid
     *
     * @mbg.generated Tue Oct 30 19:06:11 CST 2018
     */
    public void setTid(String tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_refund.oid
     *
     * @return the value of trade_refund.oid
     *
     * @mbg.generated Tue Oct 30 19:06:11 CST 2018
     */
    public String getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_refund.oid
     *
     * @param oid the value for trade_refund.oid
     *
     * @mbg.generated Tue Oct 30 19:06:11 CST 2018
     */
    public void setOid(String oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_refund.refund_type
     *
     * @return the value of trade_refund.refund_type
     *
     * @mbg.generated Tue Oct 30 19:06:11 CST 2018
     */
    public String getRefundType() {
        return refundType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_refund.refund_type
     *
     * @param refundType the value for trade_refund.refund_type
     *
     * @mbg.generated Tue Oct 30 19:06:11 CST 2018
     */
    public void setRefundType(String refundType) {
        this.refundType = refundType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_refund.refunded_fee
     *
     * @return the value of trade_refund.refunded_fee
     *
     * @mbg.generated Tue Oct 30 19:06:11 CST 2018
     */
    public BigDecimal getRefundedFee() {
        return refundedFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_refund.refunded_fee
     *
     * @param refundedFee the value for trade_refund.refunded_fee
     *
     * @mbg.generated Tue Oct 30 19:06:11 CST 2018
     */
    public void setRefundedFee(BigDecimal refundedFee) {
        this.refundedFee = refundedFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_refund.refund_reason
     *
     * @return the value of trade_refund.refund_reason
     *
     * @mbg.generated Tue Oct 30 19:06:11 CST 2018
     */
    public String getRefundReason() {
        return refundReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_refund.refund_reason
     *
     * @param refundReason the value for trade_refund.refund_reason
     *
     * @mbg.generated Tue Oct 30 19:06:11 CST 2018
     */
    public void setRefundReason(String refundReason) {
        this.refundReason = refundReason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_refund.version
     *
     * @return the value of trade_refund.version
     *
     * @mbg.generated Tue Oct 30 19:06:11 CST 2018
     */
    public String getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_refund.version
     *
     * @param version the value for trade_refund.version
     *
     * @mbg.generated Tue Oct 30 19:06:11 CST 2018
     */
    public void setVersion(String version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_refund.update_time
     *
     * @return the value of trade_refund.update_time
     *
     * @mbg.generated Tue Oct 30 19:06:11 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_refund.update_time
     *
     * @param updateTime the value for trade_refund.update_time
     *
     * @mbg.generated Tue Oct 30 19:06:11 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}