package com.tasly.yzpt.repository.message.entity;

import java.util.Date;

public class TradeWms {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_wms.tid
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private String tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_wms.status
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private Boolean status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_wms.message
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private String message;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_wms.send_time
     *
     * @mbg.generated Thu Oct 25 10:50:43 CST 2018
     */
    private Date sendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_wms.return_time
     *
     * @mbg.generated Thu Oct 25 10:50:43 CST 2018
     */
    private Date returnTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_wms.tid
     *
     * @return the value of trade_wms.tid
     *
     * @mbg.generated Thu Oct 25 10:50:43 CST 2018
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_wms.tid
     *
     * @param tid the value for trade_wms.tid
     *
<<<<<<< Updated upstream
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
=======
     * @mbg.generated Thu Oct 25 10:50:43 CST 2018
>>>>>>> Stashed changes
     */
    public void setTid(String tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_wms.status
     *
     * @return the value of trade_wms.status
     *
     * @mbg.generated Thu Oct 25 10:50:43 CST 2018
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_wms.status
     *
     * @param status the value for trade_wms.status
     *
     * @mbg.generated Thu Oct 25 10:50:43 CST 2018
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_wms.message
     *
     * @return the value of trade_wms.message
     *
     * @mbg.generated Thu Oct 25 10:50:43 CST 2018
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_wms.message
     *
     * @param message the value for trade_wms.message
     *
     * @mbg.generated Thu Oct 25 10:50:43 CST 2018
     */
    public void setMessage(String message) {
        this.message = message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_wms.send_time
     *
     * @return the value of trade_wms.send_time
     *
     * @mbg.generated Thu Oct 25 10:50:43 CST 2018
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_wms.send_time
     *
     * @param sendTime the value for trade_wms.send_time
     *
     * @mbg.generated Thu Oct 25 10:50:43 CST 2018
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_wms.return_time
     *
     * @return the value of trade_wms.return_time
     *
     * @mbg.generated Thu Oct 25 10:50:43 CST 2018
     */
    public Date getReturnTime() {
        return returnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_wms.return_time
     *
     * @param returnTime the value for trade_wms.return_time
     *
     * @mbg.generated Thu Oct 25 10:50:43 CST 2018
     */
    public void setReturnTime(Date returnTime) {
        this.returnTime = returnTime;
    }
}