package com.tasly.yzpt.repository.message.entity;

import java.util.Date;

public class TradeAddress {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_address.tid
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    private String tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_address.receiver_name
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    private String receiverName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_address.receiver_tel
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    private String receiverTel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_address.delivery_province
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    private String deliveryProvince;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_address.delivery_city
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    private String deliveryCity;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_address.delivery_district
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    private String deliveryDistrict;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_address.delivery_address
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    private String deliveryAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_address.address_extra
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    private String addressExtra;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_address.delivery_postal_code
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    private String deliveryPostalCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_address.self_fetch_info
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    private String selfFetchInfo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_address.delivery_start_time
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    private Date deliveryStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_address.delivery_end_time
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    private Date deliveryEndTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_address.tid
     *
     * @return the value of trade_address.tid
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_address.tid
     *
     * @param tid the value for trade_address.tid
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public void setTid(String tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_address.receiver_name
     *
     * @return the value of trade_address.receiver_name
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public String getReceiverName() {
        return receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_address.receiver_name
     *
     * @param receiverName the value for trade_address.receiver_name
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public void setReceiverName(String receiverName) {
        this.receiverName = receiverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_address.receiver_tel
     *
     * @return the value of trade_address.receiver_tel
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public String getReceiverTel() {
        return receiverTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_address.receiver_tel
     *
     * @param receiverTel the value for trade_address.receiver_tel
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public void setReceiverTel(String receiverTel) {
        this.receiverTel = receiverTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_address.delivery_province
     *
     * @return the value of trade_address.delivery_province
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public String getDeliveryProvince() {
        return deliveryProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_address.delivery_province
     *
     * @param deliveryProvince the value for trade_address.delivery_province
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public void setDeliveryProvince(String deliveryProvince) {
        this.deliveryProvince = deliveryProvince;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_address.delivery_city
     *
     * @return the value of trade_address.delivery_city
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public String getDeliveryCity() {
        return deliveryCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_address.delivery_city
     *
     * @param deliveryCity the value for trade_address.delivery_city
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public void setDeliveryCity(String deliveryCity) {
        this.deliveryCity = deliveryCity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_address.delivery_district
     *
     * @return the value of trade_address.delivery_district
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public String getDeliveryDistrict() {
        return deliveryDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_address.delivery_district
     *
     * @param deliveryDistrict the value for trade_address.delivery_district
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public void setDeliveryDistrict(String deliveryDistrict) {
        this.deliveryDistrict = deliveryDistrict;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_address.delivery_address
     *
     * @return the value of trade_address.delivery_address
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public String getDeliveryAddress() {
        return deliveryAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_address.delivery_address
     *
     * @param deliveryAddress the value for trade_address.delivery_address
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public void setDeliveryAddress(String deliveryAddress) {
        this.deliveryAddress = deliveryAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_address.address_extra
     *
     * @return the value of trade_address.address_extra
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public String getAddressExtra() {
        return addressExtra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_address.address_extra
     *
     * @param addressExtra the value for trade_address.address_extra
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public void setAddressExtra(String addressExtra) {
        this.addressExtra = addressExtra;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_address.delivery_postal_code
     *
     * @return the value of trade_address.delivery_postal_code
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public String getDeliveryPostalCode() {
        return deliveryPostalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_address.delivery_postal_code
     *
     * @param deliveryPostalCode the value for trade_address.delivery_postal_code
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public void setDeliveryPostalCode(String deliveryPostalCode) {
        this.deliveryPostalCode = deliveryPostalCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_address.self_fetch_info
     *
     * @return the value of trade_address.self_fetch_info
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public String getSelfFetchInfo() {
        return selfFetchInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_address.self_fetch_info
     *
     * @param selfFetchInfo the value for trade_address.self_fetch_info
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public void setSelfFetchInfo(String selfFetchInfo) {
        this.selfFetchInfo = selfFetchInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_address.delivery_start_time
     *
     * @return the value of trade_address.delivery_start_time
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public Date getDeliveryStartTime() {
        return deliveryStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_address.delivery_start_time
     *
     * @param deliveryStartTime the value for trade_address.delivery_start_time
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public void setDeliveryStartTime(Date deliveryStartTime) {
        this.deliveryStartTime = deliveryStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_address.delivery_end_time
     *
     * @return the value of trade_address.delivery_end_time
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public Date getDeliveryEndTime() {
        return deliveryEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_address.delivery_end_time
     *
     * @param deliveryEndTime the value for trade_address.delivery_end_time
     *
     * @mbg.generated Fri Oct 19 09:30:28 CST 2018
     */
    public void setDeliveryEndTime(Date deliveryEndTime) {
        this.deliveryEndTime = deliveryEndTime;
    }
}