package com.tasly.yzpt.repository.message.entity;

import java.math.BigDecimal;

public class TradeItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_item.oid
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private String oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_item.tid
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private String tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_item.item_type
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private Integer itemType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_item.title
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_item.num
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private Integer num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_item.outer_sku_id
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private String outerSkuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_item.buyer_messages
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private String buyerMessages;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_item.price
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_item.total_fee
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private BigDecimal totalFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_item.payment
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private BigDecimal payment;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_item.item_id
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private Integer itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_item.sku_id
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private Integer skuId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_item.sku_properties_name
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private String skuPropertiesName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_item.outer_item_id
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private String outerItemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_item.points_price
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private String pointsPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_item.pic_path
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private String picPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_item.goods_url
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private String goodsUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_item.alias
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private String alias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_item.is_present
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private Boolean isPresent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_item.discount_price
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private BigDecimal discountPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_item.sku_unique_code
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private String skuUniqueCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_item.pre_sale_type
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private String preSaleType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_item.is_pre_sale
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    private String isPreSale;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_item.oid
     *
     * @return the value of trade_item.oid
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public String getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_item.oid
     *
     * @param oid the value for trade_item.oid
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setOid(String oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_item.tid
     *
     * @return the value of trade_item.tid
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_item.tid
     *
     * @param tid the value for trade_item.tid
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setTid(String tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_item.item_type
     *
     * @return the value of trade_item.item_type
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public Integer getItemType() {
        return itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_item.item_type
     *
     * @param itemType the value for trade_item.item_type
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setItemType(Integer itemType) {
        this.itemType = itemType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_item.title
     *
     * @return the value of trade_item.title
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_item.title
     *
     * @param title the value for trade_item.title
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_item.num
     *
     * @return the value of trade_item.num
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public Integer getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_item.num
     *
     * @param num the value for trade_item.num
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setNum(Integer num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_item.outer_sku_id
     *
     * @return the value of trade_item.outer_sku_id
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public String getOuterSkuId() {
        return outerSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_item.outer_sku_id
     *
     * @param outerSkuId the value for trade_item.outer_sku_id
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setOuterSkuId(String outerSkuId) {
        this.outerSkuId = outerSkuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_item.buyer_messages
     *
     * @return the value of trade_item.buyer_messages
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public String getBuyerMessages() {
        return buyerMessages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_item.buyer_messages
     *
     * @param buyerMessages the value for trade_item.buyer_messages
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setBuyerMessages(String buyerMessages) {
        this.buyerMessages = buyerMessages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_item.price
     *
     * @return the value of trade_item.price
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_item.price
     *
     * @param price the value for trade_item.price
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_item.total_fee
     *
     * @return the value of trade_item.total_fee
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public BigDecimal getTotalFee() {
        return totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_item.total_fee
     *
     * @param totalFee the value for trade_item.total_fee
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setTotalFee(BigDecimal totalFee) {
        this.totalFee = totalFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_item.payment
     *
     * @return the value of trade_item.payment
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public BigDecimal getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_item.payment
     *
     * @param payment the value for trade_item.payment
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setPayment(BigDecimal payment) {
        this.payment = payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_item.item_id
     *
     * @return the value of trade_item.item_id
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public Integer getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_item.item_id
     *
     * @param itemId the value for trade_item.item_id
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setItemId(Integer itemId) {
        this.itemId = itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_item.sku_id
     *
     * @return the value of trade_item.sku_id
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public Integer getSkuId() {
        return skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_item.sku_id
     *
     * @param skuId the value for trade_item.sku_id
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setSkuId(Integer skuId) {
        this.skuId = skuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_item.sku_properties_name
     *
     * @return the value of trade_item.sku_properties_name
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public String getSkuPropertiesName() {
        return skuPropertiesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_item.sku_properties_name
     *
     * @param skuPropertiesName the value for trade_item.sku_properties_name
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setSkuPropertiesName(String skuPropertiesName) {
        this.skuPropertiesName = skuPropertiesName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_item.outer_item_id
     *
     * @return the value of trade_item.outer_item_id
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public String getOuterItemId() {
        return outerItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_item.outer_item_id
     *
     * @param outerItemId the value for trade_item.outer_item_id
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setOuterItemId(String outerItemId) {
        this.outerItemId = outerItemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_item.points_price
     *
     * @return the value of trade_item.points_price
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public String getPointsPrice() {
        return pointsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_item.points_price
     *
     * @param pointsPrice the value for trade_item.points_price
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setPointsPrice(String pointsPrice) {
        this.pointsPrice = pointsPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_item.pic_path
     *
     * @return the value of trade_item.pic_path
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public String getPicPath() {
        return picPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_item.pic_path
     *
     * @param picPath the value for trade_item.pic_path
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setPicPath(String picPath) {
        this.picPath = picPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_item.goods_url
     *
     * @return the value of trade_item.goods_url
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public String getGoodsUrl() {
        return goodsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_item.goods_url
     *
     * @param goodsUrl the value for trade_item.goods_url
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setGoodsUrl(String goodsUrl) {
        this.goodsUrl = goodsUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_item.alias
     *
     * @return the value of trade_item.alias
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_item.alias
     *
     * @param alias the value for trade_item.alias
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setAlias(String alias) {
        this.alias = alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_item.is_present
     *
     * @return the value of trade_item.is_present
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public Boolean getIsPresent() {
        return isPresent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_item.is_present
     *
     * @param isPresent the value for trade_item.is_present
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setIsPresent(Boolean isPresent) {
        this.isPresent = isPresent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_item.discount_price
     *
     * @return the value of trade_item.discount_price
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public BigDecimal getDiscountPrice() {
        return discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_item.discount_price
     *
     * @param discountPrice the value for trade_item.discount_price
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setDiscountPrice(BigDecimal discountPrice) {
        this.discountPrice = discountPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_item.sku_unique_code
     *
     * @return the value of trade_item.sku_unique_code
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public String getSkuUniqueCode() {
        return skuUniqueCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_item.sku_unique_code
     *
     * @param skuUniqueCode the value for trade_item.sku_unique_code
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setSkuUniqueCode(String skuUniqueCode) {
        this.skuUniqueCode = skuUniqueCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_item.pre_sale_type
     *
     * @return the value of trade_item.pre_sale_type
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public String getPreSaleType() {
        return preSaleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_item.pre_sale_type
     *
     * @param preSaleType the value for trade_item.pre_sale_type
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setPreSaleType(String preSaleType) {
        this.preSaleType = preSaleType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_item.is_pre_sale
     *
     * @return the value of trade_item.is_pre_sale
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public String getIsPreSale() {
        return isPreSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_item.is_pre_sale
     *
     * @param isPreSale the value for trade_item.is_pre_sale
     *
     * @mbg.generated Thu Oct 25 11:07:48 CST 2018
     */
    public void setIsPreSale(String isPreSale) {
        this.isPreSale = isPreSale;
    }
}