package com.tasly.yzpt.repository.message.entity;

public class TradeLogistics {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_logistics.tid
     *
     * @mbg.generated Fri Nov 02 11:45:27 CST 2018
     */
    private String tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_logistics.oid
     *
     * @mbg.generated Fri Nov 02 11:45:27 CST 2018
     */
    private String oid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_logistics.logistics_code
     *
     * @mbg.generated Fri Nov 02 11:45:27 CST 2018
     */
    private String logisticsCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column trade_logistics.logistics_number
     *
     * @mbg.generated Fri Nov 02 11:45:27 CST 2018
     */
    private String logisticsNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_logistics.tid
     *
     * @return the value of trade_logistics.tid
     *
     * @mbg.generated Fri Nov 02 11:45:27 CST 2018
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_logistics.tid
     *
     * @param tid the value for trade_logistics.tid
     *
     * @mbg.generated Fri Nov 02 11:45:27 CST 2018
     */
    public void setTid(String tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_logistics.oid
     *
     * @return the value of trade_logistics.oid
     *
     * @mbg.generated Fri Nov 02 11:45:27 CST 2018
     */
    public String getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_logistics.oid
     *
     * @param oid the value for trade_logistics.oid
     *
     * @mbg.generated Fri Nov 02 11:45:27 CST 2018
     */
    public void setOid(String oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_logistics.logistics_code
     *
     * @return the value of trade_logistics.logistics_code
     *
     * @mbg.generated Fri Nov 02 11:45:27 CST 2018
     */
    public String getLogisticsCode() {
        return logisticsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_logistics.logistics_code
     *
     * @param logisticsCode the value for trade_logistics.logistics_code
     *
     * @mbg.generated Fri Nov 02 11:45:27 CST 2018
     */
    public void setLogisticsCode(String logisticsCode) {
        this.logisticsCode = logisticsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column trade_logistics.logistics_number
     *
     * @return the value of trade_logistics.logistics_number
     *
     * @mbg.generated Fri Nov 02 11:45:27 CST 2018
     */
    public String getLogisticsNumber() {
        return logisticsNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column trade_logistics.logistics_number
     *
     * @param logisticsNumber the value for trade_logistics.logistics_number
     *
     * @mbg.generated Fri Nov 02 11:45:27 CST 2018
     */
    public void setLogisticsNumber(String logisticsNumber) {
        this.logisticsNumber = logisticsNumber;
    }
}