package com.tasly.yzpt.repository.message.entity;

public class YzMessage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_message.id
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_message.msg
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    private String msg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_message.send_count
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    private Integer sendCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_message.mode
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    private Integer mode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_message.app_id
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    private String appId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_message.client_id
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    private String clientId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_message.version
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    private Long version;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_message.type
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_message.sign
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    private String sign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_message.kdt_id
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    private Integer kdtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_message.status
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_message.kdt_name
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    private String kdtName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_message.asyn_status
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    private Integer asynStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yz_message.test
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    private byte[] test;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_message.id
     *
     * @return the value of yz_message.id
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_message.id
     *
     * @param id the value for yz_message.id
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_message.msg
     *
     * @return the value of yz_message.msg
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    public String getMsg() {
        return msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_message.msg
     *
     * @param msg the value for yz_message.msg
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    public void setMsg(String msg) {
        this.msg = msg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_message.send_count
     *
     * @return the value of yz_message.send_count
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    public Integer getSendCount() {
        return sendCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_message.send_count
     *
     * @param sendCount the value for yz_message.send_count
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    public void setSendCount(Integer sendCount) {
        this.sendCount = sendCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_message.mode
     *
     * @return the value of yz_message.mode
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    public Integer getMode() {
        return mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_message.mode
     *
     * @param mode the value for yz_message.mode
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    public void setMode(Integer mode) {
        this.mode = mode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_message.app_id
     *
     * @return the value of yz_message.app_id
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    public String getAppId() {
        return appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_message.app_id
     *
     * @param appId the value for yz_message.app_id
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    public void setAppId(String appId) {
        this.appId = appId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_message.client_id
     *
     * @return the value of yz_message.client_id
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    public String getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_message.client_id
     *
     * @param clientId the value for yz_message.client_id
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_message.version
     *
     * @return the value of yz_message.version
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    public Long getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_message.version
     *
     * @param version the value for yz_message.version
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    public void setVersion(Long version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_message.type
     *
     * @return the value of yz_message.type
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_message.type
     *
     * @param type the value for yz_message.type
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_message.sign
     *
     * @return the value of yz_message.sign
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_message.sign
     *
     * @param sign the value for yz_message.sign
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    public void setSign(String sign) {
        this.sign = sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_message.kdt_id
     *
     * @return the value of yz_message.kdt_id
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    public Integer getKdtId() {
        return kdtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_message.kdt_id
     *
     * @param kdtId the value for yz_message.kdt_id
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    public void setKdtId(Integer kdtId) {
        this.kdtId = kdtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_message.status
     *
     * @return the value of yz_message.status
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_message.status
     *
     * @param status the value for yz_message.status
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_message.kdt_name
     *
     * @return the value of yz_message.kdt_name
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    public String getKdtName() {
        return kdtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_message.kdt_name
     *
     * @param kdtName the value for yz_message.kdt_name
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    public void setKdtName(String kdtName) {
        this.kdtName = kdtName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_message.asyn_status
     *
     * @return the value of yz_message.asyn_status
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    public Integer getAsynStatus() {
        return asynStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_message.asyn_status
     *
     * @param asynStatus the value for yz_message.asyn_status
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    public void setAsynStatus(Integer asynStatus) {
        this.asynStatus = asynStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yz_message.test
     *
     * @return the value of yz_message.test
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    public byte[] getTest() {
        return test;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yz_message.test
     *
     * @param test the value for yz_message.test
     *
     * @mbg.generated Mon Sep 10 10:33:36 CST 2018
     */
    public void setTest(byte[] test) {
        this.test = test;
    }
}