
package com.tasly.yzpt.service.wms.send;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WmsCkkpdSoap", targetNamespace = "http://wservice.ckkpd/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WmsCkkpdSoap {


    /**
     * WMS销售出库订单下传方法（ERP>LMIS)
     * 
     * @param iREQUEST
     */
    @WebMethod(operationName = "ReceiveCkkpd", action = "http://wservice.ckkpd/ReceiveCkkpd")
    @Oneway
    @RequestWrapper(localName = "ReceiveCkkpd", targetNamespace = "http://wservice.ckkpd/", className = "com.tasly.weworkside.apprestful.controller.wms.order.send.ReceiveCkkpd")
    public void receiveCkkpd(
            @WebParam(name = "I_REQUEST", targetNamespace = "http://wservice.ckkpd/")
                    INFDATA iREQUEST);

}
