
package com.tasly.yzpt.service.wms.send;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WmsCkkpd", targetNamespace = "http://wservice.ckkpd/", wsdlLocation = "http://10.9.7.31:7001/WmsCkkpd.asmx?wsdl")
public class WmsCkkpd
    extends Service
{

    private final static URL WMSCKKPD_WSDL_LOCATION;
    private final static WebServiceException WMSCKKPD_EXCEPTION;
    private final static QName WMSCKKPD_QNAME = new QName("http://wservice.ckkpd/", "WmsCkkpd");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.9.7.31:7001/WmsCkkpd.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WMSCKKPD_WSDL_LOCATION = url;
        WMSCKKPD_EXCEPTION = e;
    }

    public WmsCkkpd() {
        super(__getWsdlLocation(), WMSCKKPD_QNAME);
    }

    public WmsCkkpd(WebServiceFeature... features) {
        super(__getWsdlLocation(), WMSCKKPD_QNAME, features);
    }

    public WmsCkkpd(URL wsdlLocation) {
        super(wsdlLocation, WMSCKKPD_QNAME);
    }

    public WmsCkkpd(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WMSCKKPD_QNAME, features);
    }

    public WmsCkkpd(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WmsCkkpd(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WmsCkkpdSoap
     */
    @WebEndpoint(name = "WmsCkkpdSoap")
    public WmsCkkpdSoap getWmsCkkpdSoap() {
        return super.getPort(new QName("http://wservice.ckkpd/", "WmsCkkpdSoap"), WmsCkkpdSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WmsCkkpdSoap
     */
    @WebEndpoint(name = "WmsCkkpdSoap")
    public WmsCkkpdSoap getWmsCkkpdSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://wservice.ckkpd/", "WmsCkkpdSoap"), WmsCkkpdSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns WmsCkkpdSoap
     */
    @WebEndpoint(name = "WmsCkkpdSoap12")
    public WmsCkkpdSoap getWmsCkkpdSoap12() {
        return super.getPort(new QName("http://wservice.ckkpd/", "WmsCkkpdSoap12"), WmsCkkpdSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WmsCkkpdSoap
     */
    @WebEndpoint(name = "WmsCkkpdSoap12")
    public WmsCkkpdSoap getWmsCkkpdSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://wservice.ckkpd/", "WmsCkkpdSoap12"), WmsCkkpdSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WMSCKKPD_EXCEPTION!= null) {
            throw WMSCKKPD_EXCEPTION;
        }
        return WMSCKKPD_WSDL_LOCATION;
    }

}
